exp_format = [
    '#FEA_NUM',
    '#JN',
    '#DIST_START',
    '#US',
    '#JL',
    '#DOC',
    '#FEATURE',
    '#FEATURE_TYPE',
    '#DESCR',
    '#LENGTH',
    '#WIDTH',
    '#DEPTH_PRC',
    '#DEPTH_MM',
    '#AMPL',
    '#DEPTH_PREV',
    '#REMARKS',
    '#ORIENT_DEG',
    '#WT',
    '#RWT',
    '#LOC',
    '#DIMM',
    '#CLUSTER',
    '#ERF',
    '#PSAFE',
    '#LAT',
    '#LONG',
    '#ALT',
    '#FEA_NUM_PREV',
    '#VTD_NUM',
    '#YEARS']

exp_format2 = [
    '#FEA_NUM',
    'HELLO',
    '#JN',
    'Дистанция, м']
